---
title: "Strutural elusidation of Plasmodium_falciparum"
author: "David A. Obe"
format: html
---

##1.0 Introduction

###1.1 RSCB Protein Data Bank (PDB)

The PDB is consortium managed by three different organization (RCSB PDB, PDBe, PDBj). These databases are held by different countries. RCSB PDB - USA, PDBe - Europe, PDBj - Japan. These organizations share data equally and ensure that access to the data bank is free and accessible to the public. PDB archive contain information on 3D structures of biological macromolecules, including proteins and nucleic acids. With the improvement in deep learning and marching learning algorithms, the PDB also holds not just experimentally resolved structures but also computationally solved structures. Understanding the structure of macromolecules can help inform the role of such macromolecule in physiological and pathological, and can help in drug development. The RCSB PDB <http://www.rcsb.org/> would be used for this study.

###1.2 *Plasmodium falciparum*
